import express from 'express';
import cors from 'cors';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { query } from './db.js';

// Configuration
dotenv.config();
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());

// API Routes
app.get('/api/health', async (req, res) => {
    try {
        const result = await query('SELECT NOW()');
        res.json({ status: 'ok', time: result.rows[0].now });
    } catch (err) {
        console.error('Database connection error', err);
        res.status(500).json({ status: 'error', message: 'Database connection failed' });
    }
});

// Auth Routes (Placeholder)
app.post('/api/auth/login', async (req, res) => {
    // TODO: Implement actual login logic with bcrypt and jwt
    const { email, password } = req.body;
    console.log(`Login attempt for: ${email}`);

    // Simulating response for now
    if (email === 'admin@adrielssystems.com' && password === 'admin') {
        res.json({ token: 'fake-jwt-token-admin', role: 'ADMIN', user: { email, name: 'Admin User' } });
    } else if (email === 'client@adrielssystems.com' && password === 'client') {
        res.json({ token: 'fake-jwt-token-client', role: 'CLIENT', user: { email, name: 'Client User' } });
    } else {
        res.status(401).json({ message: 'Invalid credentials' });
    }
});

// Serve Static Files (Production)
// In production, we serve the 'dist' folder generated by Vite
const distPath = path.join(__dirname, '../dist');
app.use(express.static(distPath));

// Fallback for SPA routing
app.use((req, res) => {
    if (req.path.startsWith('/api')) {
        // 404 for API routes
        return res.status(404).json({ message: 'API endpoint not found' });
    }
    res.sendFile(path.join(distPath, 'index.html'));
});

// Start Server
app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});
