import express from 'express';
import cors from 'cors';
import path from 'path';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { query } from './db.js';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';

// Configuration
dotenv.config();
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());

// API Routes
app.get('/api/health', async (req, res) => {
    try {
        const result = await query('SELECT NOW()');
        res.json({ status: 'ok', time: result.rows[0].now });
    } catch (err) {
        console.error('Database connection error', err);
        res.status(500).json({ status: 'error', message: 'Database connection failed' });
    }
});

// Auth Routes (Real Implementation)
app.post('/api/auth/login', async (req, res) => {
    const { email, password } = req.body;
    console.log(`Login attempt for: ${email}`);

    try {
        // Check if user exists
        const result = await query('SELECT * FROM users WHERE email = $1', [email]);

        if (result.rows.length === 0) {
            return res.status(401).json({ message: 'Invalid credentials' });
        }

        const user = result.rows[0];

        // Verify password
        const validPassword = await bcrypt.compare(password, user.password_hash);

        if (!validPassword) {
            return res.status(401).json({ message: 'Invalid credentials' });
        }

        // Generate Token
        // In production use process.env.AUTH_SECRET
        const secret = process.env.AUTH_SECRET || 'dev_secret';
        const token = jwt.sign(
            { id: user.id, email: user.email, role: user.role },
            secret,
            { expiresIn: '24h' }
        );

        // Fetch additional info if client?
        let extraInfo = {};
        if (user.role === 'CLIENT') {
            // Future: fetch client details
        }

        res.json({
            token,
            role: user.role,
            user: {
                id: user.id,
                email: user.email,
                name: user.email.split('@')[0], // Fallback name
            }
        });

    } catch (err) {
        console.error('Login error:', err);
        res.status(500).json({ message: 'Server error during login' });
    }
});

// Client Management Routes
app.get('/api/clients', async (req, res) => {
    try {
        const result = await query(`
            SELECT c.*, u.email as user_email, u.role 
            FROM clients c
            LEFT JOIN users u ON u.client_id = c.id
            ORDER BY c.created_at DESC
        `);
        res.json(result.rows);
    } catch (err) {
        console.error('Error fetching clients:', err);
        res.status(500).json({ message: 'Error fetching clients' });
    }
});

app.post('/api/clients', async (req, res) => {
    const { name, company_name, email, contact_info, password } = req.body;

    try {
        // Start transaction
        await query('BEGIN');

        // 1. Create Client
        const clientResult = await query(
            'INSERT INTO clients (name, company_name, email, contact_info) VALUES ($1, $2, $3, $4) RETURNING id',
            [name, company_name, email, contact_info]
        );
        const clientId = clientResult.rows[0].id;

        // 2. Create User (if email provided)
        if (email && password) {
            const saltRounds = 10;
            const hash = await bcrypt.hash(password, saltRounds);

            await query(
                'INSERT INTO users (email, password_hash, role, client_id) VALUES ($1, $2, $3, $4)',
                [email, hash, 'CLIENT', clientId]
            );
        }

        await query('COMMIT');

        res.status(201).json({ message: 'Client created successfully', clientId });
    } catch (err) {
        await query('ROLLBACK');
        console.error('Error creating client:', err);
        if (err.constraint === 'users_email_key' || err.constraint === 'clients_email_key') {
            return res.status(400).json({ message: 'Email already exists' });
        }
        res.status(500).json({ message: 'Error creating client' });
    }
});

// Payment Management Routes
app.get('/api/payments', async (req, res) => {
    try {
        const result = await query(`
            SELECT p.*, c.name as client_name, c.company_name, c.email as client_email
            FROM payments p
            JOIN clients c ON p.client_id = c.id
            ORDER BY p.payment_date DESC
        `);
        res.json(result.rows);
    } catch (err) {
        console.error('Error fetching payments:', err);
        res.status(500).json({ message: 'Error fetching payments' });
    }
});

// Serve Static Files (Production)
// In production, we serve the 'dist' folder generated by Vite
const distPath = path.join(__dirname, '../dist');
app.use(express.static(distPath));

// Fallback for SPA routing
app.use((req, res) => {
    if (req.path.startsWith('/api')) {
        // 404 for API routes
        return res.status(404).json({ message: 'API endpoint not found' });
    }
    res.sendFile(path.join(distPath, 'index.html'));
});

// Start Server
app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});
